# Generated by Django 3.2.7 on 2021-10-31 20:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='class', max_length=200)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 20, 12, 23, 865719, tzinfo=utc), verbose_name='date joined')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='class', max_length=200)),
                ('title', models.CharField(default='assignment name', max_length=200)),
                ('description', models.CharField(default='description', max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 20, 12, 23, 864573, tzinfo=utc), verbose_name='date created')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 20, 12, 23, 864595, tzinfo=utc), verbose_name='due date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
