# Generated by Django 3.2.7 on 2021-10-23 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.CharField(default='class', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 16, 55, 378252, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 16, 55, 378273, tzinfo=utc), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='assignment name', max_length=200),
        ),
    ]
