# Generated by Django 3.2.7 on 2021-10-30 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20211029_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 1, 41, 48, 100697, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 1, 41, 48, 100723, tzinfo=utc), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 1, 41, 48, 101362, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
