# Generated by Django 3.2.7 on 2021-10-30 02:31

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0004_auto_20211029_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 2, 31, 32, 260544, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 2, 31, 32, 260567, tzinfo=utc), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 2, 31, 32, 261497, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
