# Generated by Django 3.2.7 on 2021-10-31 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20211030_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 2, 7, 11, 667020, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 2, 7, 11, 667045, tzinfo=utc), verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 2, 7, 11, 668139, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
